#!/usr/bin/env bash

# Ansible Homelab Configuration Value Generator
# Writes generated secrets to .generated-values.env in repo root.
# By default it refuses to overwrite an existing file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${SCRIPT_DIR}/.generated-values.env"
OVERWRITE=false

if [[ "${1:-}" == "--overwrite" ]]; then
  OVERWRITE=true
fi

if [[ -f "${OUT_FILE}" && "${OVERWRITE}" != "true" ]]; then
  echo "Generated values file already exists: ${OUT_FILE}"
  echo "Refusing to overwrite existing secrets."
  echo "Use: bash generate-values.sh --overwrite"
  exit 1
fi

write_kv() {
  local key="$1"
  local value="$2"
  printf '%s="%s"\n' "${key}" "${value}" >> "${OUT_FILE}"
}

umask 077
: > "${OUT_FILE}"
cat >> "${OUT_FILE}" <<'EOF'
# Generated by generate-values.sh
# Do not commit this file. Keep it private.
EOF

write_kv "generated_at" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
write_kv "generated_by" "$(whoami)"

write_kv "immich_postgres_password" "$(openssl rand -base64 32)"
write_kv "immich_typesense_api_key" "$(openssl rand -base64 32)"
write_kv "samba_password" "$(openssl rand -base64 32)"
write_kv "pihole_password" "$(openssl rand -base64 32)"

write_kv "jwt_secret" "$(openssl rand -base64 32)"
write_kv "authelia_sqlite_encryption_key" "$(openssl rand -base64 32)"
write_kv "vnc_password" "$(openssl rand -base64 32)"
write_kv "coolify_postgres_password" "$(openssl rand -base64 32)"

echo "Generated secrets written to:"
echo "  ${OUT_FILE}"
echo ""
echo "How to apply:"
echo "  bash apply-generated-values.sh --stage 2"
echo "  bash apply-generated-values.sh --stage 3"
echo "  bash apply-generated-values.sh --key samba_password,pihole_password"
echo ""
echo "Manual values still required for Stage 3:"
echo "  domain, cloudflare_email, cloudflare_api_key, traefik_basic_auth_hash,"
echo "  google_mail, google_insecure_app_pass, authelia_admin_mail,"
echo "  authelia_admin_argon2id_pass, and optionally tailscale_auth_key."
