#!/bin/bash

# Ansible Homelab Configuration Value Generator
# This script generates all random passwords/secrets needed for the homelab setup

set -e

echo "=========================================="
echo "Ansible Homelab Configuration Generator"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Basic System Values ===${NC}"
echo ""
echo "Username: $(whoami)"
echo "PUID: $(id -u)"
echo "PGID: $(id -g)"
echo "IP Address: $(hostname -I | awk '{print $1}')"
echo "Timezone: $(timedatectl 2>/dev/null | grep 'Time zone' | awk '{print $3}' || cat /etc/timezone 2>/dev/null || echo 'America/New_York')"
echo ""

echo -e "${BLUE}=== Step 2: Home Server Services ===${NC}"
echo ""
echo "immich_postgres_password: $(openssl rand -base64 32)"
echo "immich_typesense_api_key: $(openssl rand -base64 32)"
echo "samba_password: $(openssl rand -base64 32)"
echo "pihole_password: $(openssl rand -base64 32)"
echo ""

echo -e "${BLUE}=== Step 3: Monitoring & Security ===${NC}"
echo ""
echo "jwt_secret: $(openssl rand -base64 32)"
echo "authelia_sqlite_encryption_key: $(openssl rand -base64 32)"
echo "vnc_password: $(openssl rand -base64 32)"
echo "coolify_postgres_password: $(openssl rand -base64 32)"
echo ""


echo -e "${YELLOW}=== Manual Steps Required ===${NC}"
echo ""
echo "These values require manual setup (see COMPLETE_GUIDE.md for details):"
echo ""
echo "1. domain: Your domain name (REQUIRED ONLY for Step 3)"
echo "   → Optional for Steps 1-2, REQUIRED for Step 3 (Traefik)"
echo "   → Buy from: Namecheap, Cloudflare, Google Domains"
echo "   → If skipping Step 3, you can use 'localhost' or skip this"
echo ""
echo "2. cloudflare_email: Your Cloudflare account email (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Traefik (Step 3)"
echo "   → Sign up: https://dash.cloudflare.com/sign-up"
echo ""
echo "3. cloudflare_api_key: Cloudflare API token (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Traefik (Step 3)"
echo "   → Get from: https://dash.cloudflare.com/profile/api-tokens"
echo "   → Permissions: Zone.DNS.Edit, Zone.Zone.Read"
echo ""
echo "4. traefik_basic_auth_hash: Traefik dashboard password hash (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Traefik (Step 3)"
echo "   → Run: htpasswd -nB admin"
echo "   → Install: sudo apt install apache2-utils (Ubuntu/Debian)"
echo "   → Install: sudo dnf install httpd-tools (Fedora/CentOS)"
echo ""
echo "5. google_mail: Your Gmail address (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Authelia (Step 3)"
echo "   → Use your Gmail account"
echo ""
echo "6. google_insecure_app_pass: Google App Password (16 chars) (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Authelia (Step 3)"
echo "   → Get from: https://myaccount.google.com/apppasswords"
echo "   → Requires: 2FA enabled on Google account"
echo ""
echo "7. authelia_admin_mail: Admin email for Authelia (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Authelia (Step 3)"
echo "   → Use: admin@yourdomain.com or your Gmail"
echo ""
echo "8. authelia_admin_argon2id_pass: Authelia admin password hash (REQUIRED ONLY for Step 3)"
echo "   → Only needed if deploying Authelia (Step 3)"
echo "   → Run: docker run --rm authelia/authelia:latest authelia hash-password 'YourPassword'"
echo "   → Or use: https://www.authelia.com/reference/guides/passwords/"
echo ""
echo "9. tailscale_auth_key: Tailscale VPN auth key (OPTIONAL - if using Tailscale)"
echo "   → Only needed if deploying Tailscale VPN (Step 3)"
echo "   → Get from: https://login.tailscale.com/admin/settings/keys"
echo "   → Sign up: https://tailscale.com/"
echo ""
echo -e "${GREEN}=== Next Steps ===${NC}"
echo ""
echo "1. Copy all generated values above"
echo "2. See COMPLETE_GUIDE.md for detailed instructions on manual values"
echo "3. Edit group_vars/all/vars.yml with all values"
echo "4. Test: ansible-playbook master.yml --check"
echo "5. Run: ansible-playbook master.yml"
echo ""
