#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VARS_FILE="${REPO_ROOT}/group_vars/all/vars.yml"
GUI_FILE="${REPO_ROOT}/group_vars/all/gui_apps.yml"

if [[ ! -f "${VARS_FILE}" ]]; then
  echo "Error: vars file not found at ${VARS_FILE}"
  exit 1
fi

if [[ ! -f "${GUI_FILE}" ]]; then
  echo "Error: GUI apps file not found at ${GUI_FILE}"
  exit 1
fi

# Normalize line endings for WSL/Linux usage.
sed -i 's/\r$//' "${VARS_FILE}" "${GUI_FILE}"

mapfile -t REQUESTED_APPS < <(
  awk '
    /^requested_gui_apps:/ {in_list=1; next}
    in_list && /^[^[:space:]]/ {in_list=0}
    in_list && /^[[:space:]]*-[[:space:]]*/ {
      line=$0
      sub(/^[[:space:]]*-[[:space:]]*/, "", line)
      gsub(/[[:space:]]+$/, "", line)
      if (length(line) > 0) print line
    }
  ' "${GUI_FILE}"
)

if [[ ${#REQUESTED_APPS[@]} -eq 0 ]]; then
  echo "No apps found under requested_gui_apps in ${GUI_FILE}"
  exit 1
fi

declare -a SNAP_APPS=()
declare -a PKG_APPS=()
declare -a UNRESOLVED_APPS=()

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

is_snap_app() {
  local app="$1"
  has_cmd snap && snap info "${app}" >/dev/null 2>&1
}

is_apt_app() {
  local app="$1"
  has_cmd apt-cache && apt-cache show "${app}" >/dev/null 2>&1
}

is_dnf_app() {
  local app="$1"
  has_cmd dnf && dnf info "${app}" >/dev/null 2>&1
}

for app in "${REQUESTED_APPS[@]}"; do
  # Keep existing special handling in stage1 task logic.
  if [[ "${app}" == "cursor" ]]; then
    PKG_APPS+=("${app}")
    continue
  fi

  if is_snap_app "${app}"; then
    SNAP_APPS+=("${app}")
  elif is_apt_app "${app}" || is_dnf_app "${app}"; then
    PKG_APPS+=("${app}")
  else
    UNRESOLVED_APPS+=("${app}")
  fi
done

backup_gui="${GUI_FILE}.bak.$(date +%Y%m%d%H%M%S)"
cp "${GUI_FILE}" "${backup_gui}"

{
  echo "---"
  echo "# Stage 1 GUI app configuration"
  echo "# Edit only requested_gui_apps, then run:"
  echo "#   bash scripts/prepare-gui-apps.sh"
  echo "# The script will classify apps into gui_snap_packages and gui_packages."
  echo ""
  echo "# Unsplit list entered by user."
  echo "requested_gui_apps:"
  for app in "${REQUESTED_APPS[@]}"; do
    echo "  - ${app}"
  done
  echo ""
  echo "# Generated by scripts/prepare-gui-apps.sh (do not edit manually)"
  echo "gui_snap_packages:"
  if [[ ${#SNAP_APPS[@]} -eq 0 ]]; then
    echo "  []"
  else
    for app in "${SNAP_APPS[@]}"; do
      echo "  - ${app}"
    done
  fi
  echo "gui_packages:"
  if [[ ${#PKG_APPS[@]} -eq 0 ]]; then
    echo "  []"
  else
    for app in "${PKG_APPS[@]}"; do
      echo "  - ${app}"
    done
  fi
} > "${GUI_FILE}"

# Enable GUI installs in vars.yml
if grep -qE '^install_gui_apps:' "${VARS_FILE}"; then
  sed -i -E 's/^install_gui_apps:.*/install_gui_apps: true  # Enabled by scripts\/prepare-gui-apps.sh/' "${VARS_FILE}"
else
  echo "install_gui_apps: true  # Enabled by scripts/prepare-gui-apps.sh" >> "${VARS_FILE}"
fi

echo "GUI app classification complete."
echo "Updated: ${GUI_FILE}"
echo "Backup:  ${backup_gui}"
echo "Updated: ${VARS_FILE} (install_gui_apps=true)"
echo ""
echo "Requested apps: ${#REQUESTED_APPS[@]}"
echo "Snap apps:      ${#SNAP_APPS[@]}"
echo "Package apps:   ${#PKG_APPS[@]}"
echo "Unresolved:     ${#UNRESOLVED_APPS[@]}"
if [[ ${#UNRESOLVED_APPS[@]} -gt 0 ]]; then
  echo "Unresolved app names:"
  for app in "${UNRESOLVED_APPS[@]}"; do
    echo "  - ${app}"
  done
fi
